apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-deploy
    labels:
        deploy_env: test
        product: finance
spec:
    replicas: 2
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            product: finance
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            name: nginx-demo
            labels:
                app: finance-report
                product: finance
        spec:
            containers:
              - image:  nginx:1.27
                name:  nginx