apiVersion: v1
kind: ReplicaSet
metadata: 
  name: demo-rs
  labels:
    app: demo
    env: demo
spec:
  selectors:
    matchLabels:
      app: demo
      env: demo
  replicas: 2
  template:
    metadata:
     name: nginx-demo
     labels:
      app: demo
      deploy: test
      env: demo
      public: false
    spec:
      containers:
      - name: demo
        image: nginx:1.27.4
        command: ['/bin/bash']
        args: ['-c', 'echo "Hello From Nginx"']