apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  ttlSecondsAfterFinished: 180
  template:
    spec:
      containers:
      - image: alpine
        name: demo-job
        command: ['/bin/sh']
        args: ['ls -l demo']
      restartPolicy: Never