apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - image: alpine
        name: demo-job
        command: ['/bin/sh']
        args: ['-c', "echo 'Just Job Testing'"]
      restartPolicy: Never