apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: nginx-ds-demo
  name: nginx-ds-demo
spec:
  selector:
    matchLabels:
      app: nginx-ds-demo
  template:
    metadata:
      labels:
        app: nginx-ds-demo
    spec:
      containers:
      - image: nginx:1.27
        name: nginx